---
# Collection of rust applications are taken from here
# https://www.linux.org.ru/forum/talks/15282317
#
# Before running this playbook please generate debian packages 
# Run
# cd ./docker
# bash run.sh
#
- name: Install Package
  block:
    - name: find and register package(s)
      ansible.builtin.find:
        paths: {{ ded_package_path }}
        patterns: '{{ package }}_*_amd64.deb'
      register: packages

    - name: install package(s)
      ansible.builtin.apt:
        deb: {{ item }}
      loop: {{ packages }}

#    - name: setup
    - name: clean
      ansible.builtin.files:
        path: {{ item }}
        state: absent  
      loop: {{ packages }}
